/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectostratego;

/**
 *
 * @author hnleo
 */
public class TableroPantallla extends javax.swing.JFrame {

    /**
     * Creates new form TableroPantallla
     */
    public TableroPantallla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminaciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelTablero = new javax.swing.JPanel();
        panelVillanos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelHeroes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        panelEliminaciones.setBackground(new java.awt.Color(255, 255, 51));
        panelEliminaciones.setMaximumSize(new java.awt.Dimension(200, 440));
        panelEliminaciones.setMinimumSize(new java.awt.Dimension(200, 440));
        panelEliminaciones.setPreferredSize(new java.awt.Dimension(200, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminaciones.png"))); // NOI18N

        javax.swing.GroupLayout panelEliminacionesLayout = new javax.swing.GroupLayout(panelEliminaciones);
        panelEliminaciones.setLayout(panelEliminacionesLayout);
        panelEliminacionesLayout.setHorizontalGroup(
            panelEliminacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEliminacionesLayout.setVerticalGroup(
            panelEliminacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminacionesLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelEliminaciones, java.awt.BorderLayout.LINE_END);

        panelTablero.setBackground(new java.awt.Color(255, 255, 255));
        panelTablero.setMaximumSize(new java.awt.Dimension(800, 480));
        panelTablero.setMinimumSize(new java.awt.Dimension(800, 480));

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(panelTablero, java.awt.BorderLayout.CENTER);

        panelVillanos.setBackground(new java.awt.Color(255, 0, 0));
        panelVillanos.setMaximumSize(new java.awt.Dimension(1000, 60));
        panelVillanos.setMinimumSize(new java.awt.Dimension(1000, 60));
        panelVillanos.setPreferredSize(new java.awt.Dimension(1000, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannerVillanos.png"))); // NOI18N

        javax.swing.GroupLayout panelVillanosLayout = new javax.swing.GroupLayout(panelVillanos);
        panelVillanos.setLayout(panelVillanosLayout);
        panelVillanosLayout.setHorizontalGroup(
            panelVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelVillanosLayout.setVerticalGroup(
            panelVillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVillanosLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelVillanos, java.awt.BorderLayout.PAGE_START);

        panelHeroes.setBackground(new java.awt.Color(51, 0, 255));
        panelHeroes.setMaximumSize(new java.awt.Dimension(1000, 60));
        panelHeroes.setMinimumSize(new java.awt.Dimension(1000, 60));
        panelHeroes.setPreferredSize(new java.awt.Dimension(1000, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannerHeroes.png"))); // NOI18N

        javax.swing.GroupLayout panelHeroesLayout = new javax.swing.GroupLayout(panelHeroes);
        panelHeroes.setLayout(panelHeroesLayout);
        panelHeroesLayout.setHorizontalGroup(
            panelHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeroesLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelHeroesLayout.setVerticalGroup(
            panelHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeroesLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelHeroes, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroPantallla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroPantallla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroPantallla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroPantallla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroPantallla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelEliminaciones;
    private javax.swing.JPanel panelHeroes;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JPanel panelVillanos;
    // End of variables declaration//GEN-END:variables
}
